server:
  port: 8761
  

eureka:
  client:
    registerWithEureka: false  #telling the server not to register himself in the service registry
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0  #wait time for subsequent sync
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: false  

    
---
spring:
  profiles: production
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
  instance:
    preferIpAddress: true
