
server:
  port: 8989

turbine:
  appConfig: flight-management-flights-service, flight-management-booking-service, flight-management-passenger-service
  aggregator:
    clusterConfig: FLIGHT-MANAGEMENT-FLIGHTS-SERVICE,FLIGHT-MANAGEMENT-BOOKING-SERVICE,FLIGHT-MANAGEMENT-PASSENGER-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


---
spring:
  profiles: production
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
  instance:
    preferIpAddress: true
